openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub Zen API
  description: >-
    The GitHub Zen API is a simple, lighthearted endpoint that returns a random
    piece of philosophical or inspirational wisdom from GitHub's design
    philosophy when called. This playful API serves no functional purpose in
    application development but instead offers a moment of reflection, often
    sharing pithy sayings about software development, collaboration, or design
    principles that embody GitHub's cultural values. Developers sometimes use it
    as a simple test endpoint to verify API connectivity, as an Easter egg in
    applications, or simply to get a bit of inspiration during their coding
    sessionsâ€”it's GitHub's way of adding a human touch to their technical
    platform.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: ghes
  x-github-release: 3.9
tags:
  - Zen
servers:
  - url: '{protocol}://{hostname}/api/v3'
    variables:
      hostname:
        description: Self-hosted Enterprise Server hostname
        default: HOSTNAME
      protocol:
        description: Self-hosted Enterprise Server protocol
        default: http
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
paths:
  /zen:
    get:
      summary: Get The Zen Of Github
      description: Get a random sentence from the Zen of GitHub
      tags:
        - Get
        - Zen
      operationId: getTheZenOfGithub
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/meta/meta#get-the-zen-of-github
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: string
              examples:
                default:
                  summary: Example response
                  value: Responsive is better than fast
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
      security:
        - bearerHttpAuthentication: []
components:
  examples: {}
  reponses: {}
  parameters: {}
  schemas: {}
  responses: {}
  headers: {}
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
