openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub Octocat API
  description: >-
    Offers a basic endpoint to fetch the Octocat as ASCII art and provides a
    default Octocat image URL. 
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: ghes
  x-github-release: 3.9
tags:
  - Octocat
servers:
  - url: '{protocol}://{hostname}/api/v3'
    variables:
      hostname:
        description: Self-hosted Enterprise Server hostname
        default: HOSTNAME
      protocol:
        description: Self-hosted Enterprise Server protocol
        default: http
externalDocs:
  description: GitHub Enterprise Developer Docs
  url: https://docs.github.com/enterprise-server@3.9/rest/
paths:
  /octocat:
    get:
      summary: Get Octocat
      description: >-
        The GitHub Octocat API endpoint allows users to retrieve an ASCII art
        representation of GitHub's mascot, Octocat, by sending a GET request to
        the /octocat path. This simple API operation returns the iconic Octocat
        image in text format, which can be customized with an optional query
        parameter to display different speech bubble messages. It's primarily
        used for fun, testing purposes, or as an Easter egg in applications,
        demonstrating GitHub's playful side while providing developers with a
        lighthearted way to verify API connectivity.
      tags:
        - Get
        - Octocat
      operationId: getOctocat
      parameters:
        - name: s
          in: query
          description: The words to show in Octocat's speech bubble
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Response
          content:
            application/octocat-stream:
              schema:
                type: string
              examples:
                default:
                  $ref: '#/components/examples/octocat'
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/meta/meta#get-octocat
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
      security:
        - bearerHttpAuthentication: []
components:
  examples:
    octocat:
      value: |2
                       MMM.           .MMM
                       MMMMMMMMMMMMMMMMMMM
                       MMMMMMMMMMMMMMMMMMM      ___________________________________
                      MMMMMMMMMMMMMMMMMMMMM    |                                   |
                     MMMMMMMMMMMMMMMMMMMMMMM   | Avoid administrative distraction. |
                    MMMMMMMMMMMMMMMMMMMMMMMM   |_   _______________________________|
                    MMMM::- -:::::::- -::MMMM    |/
                     MM~:~ 00~:::::~ 00~:~MM
                .. MMMMM::.00:::+:::.00::MMMMM ..
                      .MM::::: ._. :::::MM.
                         MMMM;:::::;MMMM
                  -MM        MMMMMMM
                  ^  M+     MMMMMMMMM
                      MMMMMMM MM MM MM
                           MM MM MM MM
                           MM MM MM MM
                        .~~MM~MM~MM~MM~~.
                     ~~~~MM:~MM~~~MM~:MM~~~~
                    ~~~~~~==~==~~~==~==~~~~~~
                     ~~~~~~==~==~==~==~~~~~~
                         :~==~==~==~==~~  
  reponses: {}
  parameters: {}
  schemas: {}
  responses: {}
  headers: {}
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer Token
      type: http
      scheme: Bearer
